export const EVENT_CHANGE_CURRENT_TAB_BY_BG = 'EVENT_CHANGE_CURRENT_TAB_BY_BG'

export const EVENT_OPEN_URL_SP2BG = 'EVENT_OPEN_URL_SP2BG'
export const EVENT_RELOAD_SP2BG = 'EVENT_RELOAD_SP2BG'
export const EVENT_REDIRECT_URL_SP2BG = 'EVENT_REDIRECT_URL_SP2BG'
export const EVENT_REMOVE_TAB_SP2BG = 'EVENT_REMOVE_TAB_SP2BG'
export const EVENT_GET_COOKIES_SP2BG = 'EVENT_GET_COOKIES_SP2BG'

export const EVENT_CHECK_TAB_STATUS_SP2BG = 'EVENT_CHECK_TAB_STATUS_SP2BG'
export const EVENT_INJECT_INTERCEPT_SCRIPT_SP2BG = 'EVENT_INJECT_INTERCEPT_SCRIPT_SP2BG'
